name: Auto report

on: 
  push:
  workflow_dispatch:
  #每天早上8点和下午4点自动执行
  schedule:
    - cron: '30 8,16 * * *'

jobs:
  build:
    name: report
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run report script
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python index.py "$USERNAME" "$PASSWORD"