name: Auto report

on: 
  workflow_dispatch:
  #北京时间每天早上8:30和下午4:30自动执行，Github Action默认国际标准时间
  schedule:
    - cron: '30 0,8 * * *'

jobs:
  build:
    name: report
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run report script
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        APP_ID: ${{ secrets.APP_ID }}
        API_KEY: ${{ secrets.API_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SCKEY: ${{secrets.SCKEY}}
      run: |
        python index.py "$USERNAME" "$PASSWORD" "$APP_ID" "$API_KEY" "$SECRET_KEY" "$SCKEY"

    - name: 'Send mail'
      uses: dawidd6/action-send-mail@master
      if: ${{ failure() }}
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}    
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: 健康打卡——失败
        body: file://log.txt
        # 默认发送给自己，可自定义
        to: ${{ secrets.MAIL_USERNAME }}
        from: GitHub Actions